kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
    - hostPath: C:/Users/Hlynur/OneDrive/Documents/GitHub/mainproject/version-two
      containerPath: /var/www
    - hostPath: C:/Users/Hlynur/OneDrive/Documents/GitHub/Data/Redis
      containerPath: /data
    - hostPath: C:/Users/Hlynur/OneDrive/Documents/GitHub/Data/Orders
      containerPath: /orders
    - hostPath: C:/Users/Hlynur/OneDrive/Documents/GitHub/Data/Seq
      containerPath: /seq
    - hostPath: C:/Users/Hlynur/OneDrive/Documents/GitHub/Data/Cassandra
      containerPath: /cassandra
    - hostPath: C:/Users/Hlynur/OneDrive/Documents/GitHub/Data/Prometheus
      containerPath: /prometheus
    - hostPath: C:/Users/Hlynur/OneDrive/Documents/GitHub/Data/Mysqldb
      containerPath: /mysqldb
    - hostPath: C:/Users/Hlynur/OneDrive/Documents/GitHub/mainproject/products
      containerPath: /products